trunk/source/src/main/java/ar/edu/utn/sigmaproject/domain/security/User.java
package ar.edu.utn.sigmaproject.domain.security;

import ar.edu.utn.sigmaproject.domain.IdentificableEntity;
import org.hibernate.annotations.ForeignKey;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Entity
public class User extends IdentificableEntity implements Serializable {

    private static final long serialVersionUID = 771480672471939569L;

    private String firstName;
    private String lastName;
    private String username;
    private String email;
    private String password;
    private List<Role> roles = new ArrayList<Role>();

    public User() {
        super();
    }

    @Transient
    public String getCompleteName() {
        return lastName + ", " + firstName;
    }

    @Column(length = 255)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(length = 255)
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(length = 255)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(length = 255)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Column(length = 255)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @ManyToMany
    @JoinTable(joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    @ForeignKey(name = "fk_user_role_user", inverseName = "fk_user_role_role")
    @OrderColumn(name = "user_role_idx")
    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", uid=" + uid + ", firstName=" + firstName
                + ", lastName=" + lastName + ", username=" + username
                + ", password=" + password + ", email=" + email + ", roles="
                + roles + "]";
    }
}

trunk/source/src/main/java/ar/edu/utn/sigmaproject/controller/administration/RoleController.java
package ar.edu.utn.sigmaproject.controller.administration;

import ar.edu.utn.sigmaproject.controller.AbstractController;
import ar.edu.utn.sigmaproject.controller.AbstractModel;
import ar.edu.utn.sigmaproject.domain.filter.RoleFilter;
import ar.edu.utn.sigmaproject.domain.security.Permission;
import ar.edu.utn.sigmaproject.domain.security.Role;
import ar.edu.utn.sigmaproject.service.AbstractService;
import ar.edu.utn.sigmaproject.service.RoleService;
import ar.edu.utn.sigmaproject.view.datamodel.DefaultSelectionDataModelListener;
import ar.edu.utn.sigmaproject.view.datamodel.SelectableDataModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import java.util.HashSet;

@Controller("roleController")
@Scope
public class RoleController extends AbstractController<Role> {

	@Autowired
	private RoleService service;

	@Autowired
	private RoleModel model;

    @Override
	public void init() {
        super.init();
		model.setFilter(new RoleFilter());
	}

    @Override
    protected void bindModelToEntity() {
        Role editedRole = model.getEditedEntity();
        editedRole.setName(model.getName());
        editedRole.setDescription(model.getDescription());
        editedRole.getPermissions().clear();
        editedRole.getPermissions().addAll(
                model.getPermissionSelectionListener()
                        .getSelectedElements());
    }

    @Override
    protected void bindEntityToModel() {
        Role editedRole = model.getEditedEntity();
        model.setName(editedRole.getName());
        model.setDescription(editedRole.getDescription());

        DefaultSelectionDataModelListener<Permission> selectionListener = new DefaultSelectionDataModelListener<Permission>(
                new HashSet<Permission>(editedRole.getPermissions()));
        SelectableDataModel<Permission> permissionDataModel = new SelectableDataModel<Permission>(
                service.getAllPermissions(), selectionListener);
        model.setPermissionsDataModel(permissionDataModel);
        model.setPermissionSelectionListener(selectionListener);
    }

    @Override
    protected Class<Role> getEntityClass() {
        return Role.class;
    }

    @Override
    protected AbstractModel<Role> getModel() {
        return model;
    }

    @Override
    protected AbstractService<Role> getService() {
        return service;
    }
}

trunk/source/src/main/java/ar/edu/utn/sigmaproject/controller/administration/UserController.java
package ar.edu.utn.sigmaproject.controller.administration;

import ar.edu.utn.sigmaproject.controller.AbstractController;
import ar.edu.utn.sigmaproject.controller.AbstractModel;
import ar.edu.utn.sigmaproject.domain.filter.UserFilter;
import ar.edu.utn.sigmaproject.domain.security.Role;
import ar.edu.utn.sigmaproject.domain.security.User;
import ar.edu.utn.sigmaproject.service.AbstractService;
import ar.edu.utn.sigmaproject.service.UserService;
import ar.edu.utn.sigmaproject.view.datamodel.DefaultSelectionDataModelListener;
import ar.edu.utn.sigmaproject.view.datamodel.SelectableDataModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashSet;

@Controller("userController")
@Scope
public class UserController extends AbstractController<User> {

	@Autowired
	private UserService service;

	@Autowired
	private UserModel model;

    @Override
	public void init() {
        super.init();
		model.setFilter(new UserFilter());
	}

    @Override
    protected void bindModelToEntity() {
        User editedUser = model.getEditedEntity();
        editedUser.setFirstName(model.getFirstName());
        editedUser.setLastName(model.getLastName());
        editedUser.setEmail(model.getEmail());
        editedUser.setUsername(model.getUsername());
        if (model.isNewMode()) {
            editedUser.setPassword(model.getPassword());
        }
        editedUser.getRoles().clear();
        editedUser.getRoles().addAll(
                model.getRolesSelectionListener().getSelectedElements());
    }

    @Override
    protected void bindEntityToModel() {
        User editedUser = model.getEditedEntity();
        model.setFirstName(editedUser.getFirstName());
        model.setLastName(editedUser.getLastName());
        model.setEmail(editedUser.getEmail());
        model.setUsername(editedUser.getUsername());
        model.setPassword(editedUser.getPassword());
        DefaultSelectionDataModelListener<Role> selectionListener = new DefaultSelectionDataModelListener<Role>(
                new HashSet<Role>(editedUser.getRoles()));
        SelectableDataModel<Role> permissionDataModel = new SelectableDataModel<Role>(
                service.getAllRoles(), selectionListener);
        model.setRolesDataModel(permissionDataModel);
        model.setRolesSelectionListener(selectionListener);
    }

    @Override
    protected Class<User> getEntityClass() {
        return User.class;
    }

    public void save() {
		service.saveUser(model.getEditedEntity(), model.isNewMode());
	}

	public void prepareResetPassword() {
		model.setPassword(null);
		model.setConfirmPassword(null);
	}

    @Transactional(readOnly = true)
	public void confirmResetPassword() {
		User editedUser = model.getEditedEntity();
		editedUser.setPassword(model.getPassword());
        // The password should be hashed, so true is passed as argument
		service.saveUser(editedUser, true);
	}

    @Override
    protected AbstractModel getModel() {
        return model;
    }

    @Override
    protected AbstractService getService() {
        return service;
    }
}

trunk/source/src/main/webapp/WEB-INF/flows/administration/users/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/WEB-INF/templates/masterLayout.xhtml">

	<ui:define name="title">#{resourceBundle['user.admin.title']}</ui:define>
	<ui:define name="body_title">#{resourceBundle['user.admin.title']}</ui:define>

	<ui:define name="body">
		<h:form id="editUserForm">
			<h:panelGrid columns="3" width="60%">

				<h:outputText value="#{resourceBundle['user.admin.username']}:" />
				<p:inputText value="#{userModel.username}" id="username"
					label="#{resourceBundle['user.admin.username']}" size="60"
					autocomplete="off">
					<f:validateRequired />
					<f:validateLength maximum="10" />
				</p:inputText>
				<p:message for="username" />

				<h:outputText value="#{resourceBundle['user.admin.password']}:"
					rendered="#{userModel.newMode}" />
				<p:password value="#{userModel.password}" id="password"
					label="#{resourceBundle['user.admin.password']}" size="60"
					autocomplete="off" rendered="#{userModel.newMode}">
					<f:validateRequired />
					<f:validateLength maximum="255" />
				</p:password>
				<p:message for="password" rendered="#{userModel.newMode}" />

				<h:outputText value="#{resourceBundle['user.admin.firstName']}:" />
				<p:inputText value="#{userModel.firstName}" id="firstName"
					label="#{resourceBundle['user.admin.firstName']}" size="60">
					<f:validateRequired />
					<f:validateLength maximum="255" />
				</p:inputText>
				<p:message for="firstName" />

				<h:outputText value="#{resourceBundle['user.admin.lastName']}:" />
				<p:inputText value="#{userModel.lastName}" id="lastName"
					label="#{resourceBundle['user.admin.lastName']}" size="60">
					<f:validateRequired />
					<f:validateLength maximum="255" />
				</p:inputText>
				<p:message for="lastName" />

				<h:outputText value="#{resourceBundle['user.admin.email']}:" />
				<p:inputText value="#{userModel.email}" id="email"
					label="#{resourceBundle['user.admin.email']}" size="60"
					validatorMessage="#{resourceBundle['user.admin.email.invalid']}">
					<f:validateRequired />
					<f:validateLength maximum="255" />
					<f:validateRegex
						pattern="^(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([;.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$" />
				</p:inputText>
				<p:message for="email" />

			</h:panelGrid>

			<br />
			<br />

			<p:dataTable var="role" value="#{userModel.rolesDataModel}">
				<p:column>
					<f:facet name="header">
						<h:outputText value="#{resourceBundle['user.admin.roles']}" />
					</f:facet>
					<h:outputText value="#{role.wrapped.name}" />
				</p:column>

				<p:column width="10">
					<h:selectBooleanCheckbox value="#{role.selected}">
						<p:ajax />
					</h:selectBooleanCheckbox>
				</p:column>
			</p:dataTable>

			<br />

			<p:commandButton value="#{resourceBundle['accept']}" action="confirm"
				update="@form" />

			<p:commandButton value="#{resourceBundle['cancel']}" action="cancel"
				immediate="true" />
		</h:form>
	</ui:define>
</ui:composition>
</html>

trunk/source/src/main/webapp/WEB-INF/flows/administration/users/resetPassword.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">


<p:dialog id="resetPasswordDialog" header="Modal Dialog" widgetVar="resetPasswordDialog" modal="true" height="100">

	<h:form id="resetPasswordForm">
		<h:panelGrid columns="3" width="60%" id="resetPasswordGrid">
			<h:outputText value="#{resourceBundle['user.admin.username']}:" />
			<h:outputText value="#{userModel.editedUser.username}"/>
			<h:outputText/>
		
			<h:outputText value="#{resourceBundle['user.admin.password']}:" />
			<p:password value="#{userModel.password}" id="password"
				label="#{resourceBundle['user.admin.password']}" size="60"
				autocomplete="off"
				tabindex="0">
				<f:validateRequired />
				<f:validateLength maximum="10" />
			</p:password>
			<p:message for="password" />

			<h:outputText
				value="#{resourceBundle['user.admin.password.confirm']}:" />
			<p:password value="#{userModel.confirmPassword}"
				id="confirmPassword"
				label="#{resourceBundle['user.admin.password.confirm']}" size="60"
				autocomplete="off"
				tabindex="1">
				<f:validateRequired />
				<f:validateLength maximum="10" />
			</p:password>
			<p:message for="confirmPassword" />
		</h:panelGrid>
		<br />
		<br />
		<p:commandButton value="#{resourceBundle['accept']}"
			action="confirmResetPassword"
			oncomplete="if (#{facesContext.maximumSeverity==null}) {resetPasswordDialog.hide();}"
			process="resetPasswordForm"/>
		<p:commandButton value="#{resourceBundle['cancel']}"
			onclick="resetPasswordDialog.hide(); return false;" />
	</h:form>
	</p:dialog>  
</html>

trunk/source/src/main/webapp/WEB-INF/flows/administration/users/search.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/WEB-INF/templates/masterLayout.xhtml">

	<ui:define name="title">#{resourceBundle['user.search.title']}</ui:define>
	<ui:define name="body_title">#{resourceBundle['user.search.title']}</ui:define>
	
	<ui:define name="body">
		<h:form id="searchUserForm">	
				<h:panelGrid columns="5" width="60%">
				<h:outputText value="#{resourceBundle['name']}:" />
				<p:inputText value="#{userModel.filter.name}" size="60"
					id="nameFilter" />
				<p:message for="nameFilter" />
				<p:commandButton value="#{resourceBundle['search']}"
					action="search" update="userListTable" />
				<p:commandButton value="#{resourceBundle['new']}" action="new" />
			</h:panelGrid>

			<br />

			<p:dataTable id="userListTable"
				var="user" value="#{userModel.userList}"
				paginator="true"
				paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
				rowsPerPageTemplate="5,10,15"
				emptyMessage="#{resourceBundle['search.message.dataNotFound']}"
				paginatorAlwaysVisible="false">
	
				<p:column>
					<f:facet name="header">
						<h:outputText
								value="#{resourceBundle['user.admin.username']}" />
					</f:facet>
					<h:outputText value="#{user.username}" />
				</p:column>
				<p:column>
					<f:facet name="header">
						<h:outputText
							value="#{resourceBundle['user.admin.completeName']}" />
					</f:facet>
					<h:outputText value="#{user.completeName}" />
				</p:column>
				<p:column>
					<p:commandLink action="edit" title="#{resourceBundle['edit']}">
						<h:graphicImage value="/resources/images/edit.gif" />
						<f:setPropertyActionListener target="#{userModel.editedUser}"
							value="#{user}" />
					</p:commandLink>
					 						
					<p:commandLink action="prepareResetPassword"
						title="#{resourceBundle['user.admin.resetPassword']}"
						oncomplete="resetPasswordDialog.show();"
						update=":resetPasswordForm:resetPasswordGrid">
						<h:graphicImage value="/resources/images/password.png" />
						<f:setPropertyActionListener target="#{userModel.editedUser}"
							value="#{user}" />
					</p:commandLink>
					
					<p:commandLink process="@this" update="@none"
						oncomplete="confirmation.show();"
						title="#{resourceBundle['delete']}">
						<h:graphicImage value="/resources/images/delete.gif" />
						<f:setPropertyActionListener target="#{userModel.editedUser}"
							value="#{user}" />
					</p:commandLink>
					
				</p:column>
			</p:dataTable>

			<p:confirmDialog id="confirmDialog"
				message="#{resourceBundle['user.delete.confirm']}"
				header="#{resourceBundle['confirm']}" severity="alert"
				widgetVar="confirmation">

				<p:commandButton id="confirm" value="#{resourceBundle['delete']}"
					oncomplete="confirmation.hide()" action="delete"
					update="userListTable" />
				<p:commandButton id="decline" value="#{resourceBundle['cancel']}"
					onclick="confirmation.hide()" type="button" />
			</p:confirmDialog>			
		</h:form>

		<ui:include src="resetPassword.xhtml"/>
		
	</ui:define>
</ui:composition>
</html>