trunk/source/src/main/java/ar/edu/utn/sigmaproject/domain/Name.java
package ar.edu.utn.sigmaproject.domain;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.util.StringUtils;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * User: Gian Franco Zabarino
 * Date: 19/08/12
 */
@Embeddable
public class Name implements Serializable {

    private String first = "";

    private String last = "";

    public Name() {}

    public Name(String arg) {
        if (arg == null) {
            return;
        }

        // change the name from "Meadows, Rob" to "Rob Meadows"
        Pattern commaPattern = Pattern.compile("^(\\w+),\\s?");
        Matcher matcher = commaPattern.matcher(arg);
        String toParse;
        if (matcher.find()) {
            String lastName = matcher.group(1);
            String firstName = arg.replace(lastName+",", "");
            toParse = firstName + " " + lastName;
        } else {
            toParse = arg;
        }

        // clean up garbage characters from the string
        toParse = toParse.replaceAll("[^a-zA-Z0-9 ]", "");


        String[] names = toParse.trim().split(" ");

        if (names.length == 0)
            return;

        switch (names.length) {
            case 1:
                setFirst(names[0]);
                break;
            case 2:
                setFirst(names[0]);
                setLast(names[1]);
                break;
            case 3:
                setFirst(names[0] + " " + names[1]);
                setLast(names[2]);
                break;
            default:
                setFirst(StringUtils.arrayToDelimitedString(Arrays.asList(names).subList(0, names.length - 2).toArray(), " "));
                setLast(names[names.length-1]);
        }
    }

    /**
     * @return true if all name fields are blank
     */
    @Transient
    public boolean isBlank() {
        return !StringUtils.hasText(first) &&
                !StringUtils.hasText(last);
    }

    /**
     * @return true if any name field is not blank.
     */
    @Transient
    public boolean isNotBlank() {
        return !isBlank();
    }

    @Transient
    public String getFullName() {
        return (first + " " + last).trim();
    }

    @Transient
    public String getSortName() {
        return (last + ", " + first).trim();
    }

    @NotNull
    @Column(name="firstname", nullable=false)
    @NotEmpty
    public String getFirst() {
        return first;
    }
    public void setFirst(String first) {
        this.first = first.trim();
    }

    /**
     * @return true if first name is blank.
     */
    public boolean hasFirst() {
        return StringUtils.hasText(first);
    }

    @NotNull
    @Column(name="lastname", nullable=false)
    @NotEmpty
    public String getLast() {
        return last;
    }
    public void setLast(String last) {
        this.last = last.trim();
    }

    /**
     * @return true if last name is blank.
     */
    public boolean hasLast() {
        return StringUtils.hasText(last);
    }

    @Override
    public String toString() {
        return getFirst() + " " + getLast();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Name)) return false;

        Name name = (Name) o;

        if (first != null ? !first.equals(name.first) : name.first != null) return false;
        if (last != null ? !last.equals(name.last) : name.last != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = first != null ? first.hashCode() : 0;
        result = 31 * result + (last != null ? last.hashCode() : 0);
        return result;
    }
}

trunk/source/src/main/java/ar/edu/utn/sigmaproject/domain/Supplier.java
package ar.edu.utn.sigmaproject.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

/**
 * User: Gian Franco Zabarino
 * Date: 19/08/12
 */
@Entity
@DiscriminatorValue("supplier")
public class Supplier extends Person {

}

trunk/source/src/main/java/ar/edu/utn/sigmaproject/controller/SupplierController.java
package ar.edu.utn.sigmaproject.controller;

import ar.edu.utn.sigmaproject.domain.City;
import ar.edu.utn.sigmaproject.domain.IdentificableEntity;
import ar.edu.utn.sigmaproject.domain.State;
import ar.edu.utn.sigmaproject.domain.Supplier;
import ar.edu.utn.sigmaproject.domain.filter.SupplierFilter;
import ar.edu.utn.sigmaproject.service.AbstractService;
import ar.edu.utn.sigmaproject.service.AddressService;
import ar.edu.utn.sigmaproject.service.PersonService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.util.CollectionUtils;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import java.util.List;

/**
 * User: Gian Franco Zabarino
 * Date: 23/08/12
 */
@Controller("supplierController")
public class SupplierController extends AbstractController<Supplier> {

    @Autowired
    private SupplierModel model;

    @Autowired
    private PersonService<Supplier> service;

    @Autowired
    private AddressService addressService;

    @Override
    public void init() {
        super.init();
        model.setFilter(new SupplierFilter());
        model.setIdentityTypes(service.getEntityTypes());
    }

    public void populateNonEntityPropertiesToModel() {
        model.setIdentityTypes(service.getEntityTypes());
        List<State> states = addressService.findAllStates();
        model.setStates(states);
        /* If the view is rendered for the first time, the model's state will not be set.
         * We set it here, so the view can render it's cities
         */
        if (model.getState() == null && !CollectionUtils.isEmpty(states)) {
            model.setState(states.get(0));
        }
        updateStateCities();
    }

    public void prepareEditCity() {
        addressService.markCityForUpdate(model.getCity());
    }

    public void prepareEditState() {
        addressService.markStateForUpdate(model.getState());
    }

    public void setCityWithUid(String uid) {
        model.setCity(addressService.findCityByUid(uid));
    }

    public void setStateWithUid(String uid) {
        model.setState(addressService.findStateByUid(uid));
    }

    public void updateStateCities() {
        if (model.getState() != null) {
            List<City> cities = addressService.findStateCities(model.getState());
            model.setCities(cities);
            if (!CollectionUtils.isEmpty(cities)) {
                if (model.getCity() == null || !(model.getCity().getState().equals(model.getState()))) {
                    model.setCity(cities.get(0));
                }
            } else {
                model.setCity(null);
            }
        }
    }

    @Override
    protected AbstractModel<Supplier> getModel() {
        return model;
    }

    @Override
    protected AbstractService<Supplier> getService() {
        return service;
    }

    @Override
    protected void bindModelToEntity() {
        Supplier editedSupplier = model.getEditedEntity();
        editedSupplier.getAddress().setApartment(model.getApartment());
        editedSupplier.getAddress().setCity(model.getCity());
        editedSupplier.setEmail(model.getEmail());
        editedSupplier.getName().setFirst(model.getFirstName());
        editedSupplier.getAddress().setFloor(model.getFloor());
        editedSupplier.getIdentity().setIdentityNumber(model.getIdentityNumber());
        editedSupplier.getIdentity().setIdentityType(model.getIdentityType());
        editedSupplier.getName().setLast(model.getLastName());
        editedSupplier.getAddress().setNumber(model.getNumber());
        editedSupplier.getAddress().setStreet(model.getStreet());
        editedSupplier.setPhoneNumber(model.getPhoneNumber());
    }

    @Override
    protected void bindEntityToModel() {
        Supplier editedSupplier = model.getEditedEntity();
        model.setApartment(editedSupplier.getAddress().getApartment());
        model.setCity(editedSupplier.getAddress().getCity());
        model.setEmail(editedSupplier.getEmail());
        model.setFirstName(editedSupplier.getName().getFirst());
        model.setFloor(editedSupplier.getAddress().getFloor());
        model.setIdentityNumber(editedSupplier.getIdentity().getIdentityNumber());
        model.setIdentityType(editedSupplier.getIdentity().getIdentityType());
        model.setLastName(editedSupplier.getName().getLast());
        model.setNumber(editedSupplier.getAddress().getNumber());
        model.setState(editedSupplier.getAddress().getCity() != null ? editedSupplier.getAddress().getCity().getState() : null);
        model.setStreet(editedSupplier.getAddress().getStreet());
        model.setPhoneNumber(editedSupplier.getPhoneNumber());
    }

    @Override
    protected Class<Supplier> getEntityClass() {
        return Supplier.class;
    }
}

trunk/source/src/main/webapp/WEB-INF/flows/supplier/search/content.xhtml
<h:form id="searchSupplierForm"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://java.sun.com/jsf/core">
    <div class="search-section">
        <p:panelGrid columns="4" styleClass="no-border-panelgrid" style="float: left">
            <p:outputLabel value="#{resourceBundle['person.firstName']}:" for="first"/>
            <p:inputText id="first" value="#{supplierModel.filter.firstName}"/>
            <p:outputLabel value="#{resourceBundle['person.lastName']}:" for="last"/>
            <p:inputText id="last" value="#{supplierModel.filter.lastName}"/>
            <p:outputLabel value="#{resourceBundle['person.identityType']}:" for="identityType"/>
            <p:selectOneMenu id="identityType" value="#{supplierModel.filter.identityType}">
                <f:selectItem itemValue="#{null}" itemLabel="#{resourceBundle['all']}"/>
                <f:selectItems value="#{supplierModel.identityTypes}"/>
            </p:selectOneMenu>
            <p:outputLabel value="#{resourceBundle['person.identityNumber']}:" for="identityNumber"/>
            <p:inputText id="identityNumber" value="#{supplierModel.filter.identityNumber}"/>
        </p:panelGrid>
        <p:commandButton value="#{resourceBundle['search']}" action="search"
                         update="supplierListTable"
                         styleClass="search-button"/>
    </div>
    <p:commandButton value="#{resourceBundle['new']}" action="new" styleClass="new-button"/>

    <p:dataTable id="supplierListTable" var="supplier" value="#{supplierModel.list}"
                 paginator="true"
                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                 rowsPerPageTemplate="5,10,15"
                 emptyMessage="#{resourceBundle['search.message.dataNotFound']}"
                 paginatorAlwaysVisible="false">

        <p:column>
            <f:facet name="header">
                <h:outputText value="#{resourceBundle['name']}" />
            </f:facet>
            <h:outputText value="#{supplier.name.sortName}" />
        </p:column>
        <p:column>
            <f:facet name="header">
                <h:outputText value="#{resourceBundle['person.search.phone']}" />
            </f:facet>
            <h:outputText value="#{supplier.phoneNumber}" />
        </p:column>
        <p:column>
            <f:facet name="header">
                <h:outputText value="#{resourceBundle['person.search.address']}" />
            </f:facet>
            <h:outputText value="#{presentationUtils.formatAddress(supplier.address)}" />
        </p:column>
        <p:column>
            <p:commandLink action="edit" title="#{resourceBundle['edit']}">
                <h:graphicImage value="/resources/images/edit.gif" />
                <f:setPropertyActionListener target="#{supplierModel.editedEntity}"
                                             value="#{supplier}" />
            </p:commandLink>
            <p:commandLink process="@this" update="@none"
                           oncomplete="confirmation.show()"
                           title="#{resourceBundle['delete']}">
                <h:graphicImage value="/resources/images/delete.gif" />
                <f:setPropertyActionListener target="#{supplierModel.editedEntity}"
                                             value="#{supplier}" />
            </p:commandLink>
        </p:column>
    </p:dataTable>

    <p:confirmDialog id="confirmDialog"
                     message="#{resourceBundle['supplier.delete.confirm']}"
                     header="#{resourceBundle['confirm']}" severity="alert"
                     widgetVar="confirmation">

        <p:commandButton id="confirm" value="#{resourceBundle['delete']}"
                         oncomplete="confirmation.hide()" action="delete"
                         update="supplierListTable" />
        <p:commandButton id="decline" value="#{resourceBundle['cancel']}"
                         onclick="confirmation.hide()" type="button" />
    </p:confirmDialog>
</h:form>

trunk/source/src/main/webapp/WEB-INF/flows/supplier/search/search.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/WEB-INF/templates/masterLayout.xhtml">

	<ui:define name="title">#{resourceBundle['supplier.search.title']}</ui:define>
	<ui:define name="body_title">#{resourceBundle['supplier.search.title']}</ui:define>

	<ui:define name="body">
        <ui:include src="content.xhtml"/>
	</ui:define>
</ui:composition>
</html>